policySets: []
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: testlocalpsanth
        policies:
          customerManaged:
            - CFNUsers
groupSets: []
userSets: []
