policySets:
  - deploymentTargets:
      accounts:
        - LogArchive
    policies:
        - name: "CFNUsers"
          policy: templates/policy.yaml
roleSets:
  - deploymentTargets:
      accounts:
        - LogArchive
    roles:
      - name: testlocalpsanth
        assumedBy: []
        policies:
          customerManaged:
            - CFNUsers
groupSets: []
userSets: []
