enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: testlambda
    ignore: true
  - name: Orphaned
    ignore: true  
serviceControlPolicies: []
taggingPolicies: []
backupPolicies: []
